name: React CI/CD

on:
  pull_request:
    branches:
      - front-end

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./client

    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm run build --if-present
        working-directory: ${{ env.working-directory }}
      - run: npm run build
        working-directory: ${{ env.working-directory }}
      - name: Deploy
        run: |
          git config --global user.name 'chanjook1m'
          git config --global user.email '1z3r091@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} 
          npm run deploy
        working-directory: ${{ env.working-directory }}
